unstable_features = true
wrap_comments = true
condense_wildcard_suffixes = true
imports_layout = "Vertical"
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
struct_lit_single_line = true
trailing_comma = "Never"
use_field_init_shorthand = true
where_single_line = true
edition = "2021"
tab_spaces = 4
